### ISSUE TITLE
build requirement pinning isn't complete

### ISSUE THREAD

**Issue by jku** [MVrachev/oss-eu-2022-tutorial-mv#4]
build requirement pinning isn't complete:
* there is a requirements file but it's not used in workflow
* requirements file is called requirements.txt implying that it's the packages runtime requirements. requirements-release.txt or requirements-build.txt would make sense

**Comment by jku** [comment]
requirements file is also not in sdist

**Comment by MVrachev** [comment]
> requirements file is also not in sdist

As this file is for build requirements I don't it needs to be in `sdist`.
Also, that way we remove the possibility of installing dependencies through Test PyPI when installing this project.

**Comment by jku** [comment]
Sdist should include the sources and tooling required to build the binary distribution. I would definitely argue the requirements file is part of that tooling.

> we remove the possibility of installing dependencies through Test PyPI when installing this project

This makes no sense to me: the user calling pip decides which repository they use.

**Comment by MVrachev** [comment]
I fixed that and the workflow is using the `requirement` file and the `requirement` file is renamed to `requirements-build.txt`.
